src/posts/models.py
import datetime
from blog import db

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(120), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)

    def __repr__(self):
        return f"Post({self.title}, {self.date_posted})"

src/posts/forms.py
"""This module defines the longin and registration forms."""

from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    """This class defines the post form."""
    
    title = StringField("Title", validators=[DataRequired()])
    content = TextAreaField("Content", validators=[DataRequired()])
    submit = SubmitField("Post")

src/posts/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, abort, request
from flask_login import current_user, login_required
from blog import db
from users.models import User
from posts.models import Post
from posts.forms import PostForm

posts = Blueprint("posts", __name__)

@posts.route("/post/new", methods=["GET", "POST"])
@login_required
def create_post():
    form = PostForm()
    
    if form.validate_on_submit():
        db.session.add(Post(
            title=form.title.data,
            content=form.content.data,
            author=current_user))
        
        db.session.commit()
        
        flash("Your post has been created successfully.", "success")
        
        return redirect(url_for("main.home"))
    
    return render_template("create_post.html", form=form, legend="Write A New Blog Post")

@posts.route("/post/<int:post_id>")
def get_post(post_id):
    post = Post.query.get_or_404(post_id)
    
    return render_template("post.html", post=post)

@posts.route("/post/<int:post_id>/update", methods=["GET", "POST"])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    
    if post.author != current_user:
        abort(403)
    
    form = PostForm()
    
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        
        db.session.commit()
        
        flash("Your post has been updated successfully.", "success")
        
        return redirect(url_for("posts.get_post", post_id=post.id))
    
    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content
    
    return render_template("create_post.html", form=form, legend="Update Post")


@posts.route("/post/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    
    if post.author != current_user:
        abort(403)
    
    db.session.delete(post)
    db.session.commit()
    
    flash("Your post has been deleted successfully.", "success")
    
    return redirect(url_for("main.home"))


@posts.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get("page", 1, type=int)
    per_page = request.args.get("per_page", 5, type=int)
    
    user = User.query.filter_by(username=username).first_or_404()
    posts=Post.query.filter_by(author=user) \
        .order_by(Post.date_posted.desc()) \
        .paginate(page=page, per_page=per_page)
    
    return render_template("user_posts.html", posts=posts, user=user)

src/users/routes.py
from flask import current_app, render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, logout_user, current_user, login_required
from blog import db, bcrypt
from users.utils import save_picture
from users.forms import RegistrationForm, LoginForm, UpdateAccountForm, ResetPasswordRequestForm, ResetPasswordForm
from users.models import User
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

users = Blueprint("users", __name__)

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    
    form = RegistrationForm()
    
    if form.validate_on_submit():
        db.session.add(User(
            username=form.username.data,
            email=form.email.data,
            password=bcrypt.generate_password_hash(form.password.data).decode("utf-8")))
        
        db.session.commit()
        
        flash("Your account has been created successfully. Please login now.", "success")
        
        return redirect(url_for("users.login"))
    
    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            
            return redirect(request.args.get("next") or url_for("main.home"))
        
        flash("Login Unsuccessful. Please check email and password", "danger")
    
    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
def logout():
    logout_user()
    
    return redirect(url_for("main.home"))


@users.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
    form = UpdateAccountForm()
    
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        
        if form.photo.data:
            image_filename = save_picture(form.photo.data)
            current_user.photo = image_filename
        
        db.session.commit()
        
        flash("Your account info has been updated successfully.", "success")
        
        return redirect(url_for("users.profile")) # POST-GET-Redirect pattern.
    
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    
    return render_template("account.html", form=form)


@users.route("/reset_password_request", methods=["GET", "POST"])
def reset_password_request():
    """
    Description:
        Handles the reset password functionality.
        
        This route allows users to request a password reset by providing their email address. An email with instructions to reset the password is sent to the user's email address. If the user is already authenticated, they are redirected to the home page.
    
    ---
    Returns:
        If the form is submitted and valid, redirects to the login page after sending the password reset email.
        If the user is already authenticated, redirects to the home page.
        Otherwise, renders the reset password request form.
    """
    
    form = ResetPasswordRequestForm()
    
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        token = user.get_password_reset_token()

        server = smtplib.SMTP("smtp.gmail.com:587")
        server.ehlo("Gmail")
        server.starttls()
        server.login(current_app.config["MAIL_ADDRESS"], current_app.config["MAIL_APPWORD"])

        Message = MIMEMultipart()
        Message["From"] = current_app.config["MAIL_ADDRESS"]
        Message["To"] = user.email
        Message["Subject"] = "Password Reset Request."
        
        messageText = MIMEText(f"To reset your password, visit the following link: {url_for('users.reset_password', token=token, _external=True)}","html")
        Message.attach(messageText)

        server.sendmail(current_app.config["MAIL_ADDRESS"], user.email, Message.as_string())
        server.quit()
        
        flash("An email has been sent with instructions to reset your password.", "info")
        
        if current_user.is_authenticated:
            return redirect(url_for("main.home"))
    
        return redirect(url_for("users.login"))
    
    return render_template("reset_password_request.html", form=form)


@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_password(token):
    user = User.verify_password_reset_token(token)
    
    if not user:
        flash("Token is invalid or expired.", "warning")
        
        return redirect(url_for("users.reset_password_request"))
    
    form = ResetPasswordForm()
    
    if form.validate_on_submit():
        user.password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        db.session.commit()
        
        flash("Your password has been updated successfully.", "success")
        
        return redirect(url_for("users.login"))
    
    return render_template("reset_password_form.html", form=form)

src/templates/about.html
{% extends "layouts/base.html" %}
{% block title %}About{% endblock title %}

{% block content %}
    <h1>About Us</h1>
{% endblock content %}

src/templates/account.html
{% extends "layouts/base.html" %}
{% block title %}{{ current_user.username }}{% endblock title %}

{% block content %}
  <div class="content-section">
    <div class="media mb-4" style="background-color: #e9ddff;">
      <div class="row d-flex justify-content-center justify-content-sm-start align-items-center">
        <div class="col-auto">
          <img style="width: 125px; height: 125px;" alt="User Image" src="{{ url_for('static', filename='profile_photos/' + current_user.photo) }}">
        </div>
        
        <div class="col-auto">
          <div class="media-body pt-sm-0 pt-lg-3">
            <div class="display-4 fw-normal border-bottom-purple">{{ current_user.username }}</div>
            <div class="text-secondary">{{ current_user.email }}</div>
          </div>
        </div>
      </div>
    </div>
    
    <form method="POST" action="" enctype="multipart/form-data">
      {{ form.hidden_tag() }}
      
      <fieldset class="form-group">
        <legend class="border-bottom-purple mb-3 pb-1">Account Info</legend>
        
        <div class="form-group mb-3">
          {{ form.username.label(class="form-control-label mb-1") }}
          
          {% if form.username.errors %}
            {{ form.username(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.username.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          
          {% else %}
            {{ form.username(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        
        <div class="form-group mb-3">
          {{ form.email.label(class="form-control-label mb-1") }}
          {% if form.email.errors %}
            {{ form.email(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.email(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        
        <div class="form-group mb-3">
          {{ form.photo.label(class="mb-1") }}
          
          {{ form.photo(class="form-control form-control-file") }}
          
          {% if form.photo.errors %}
            {% for error in form.photo.errors %}
              <span class="text-danger">{{ error }}</span>
            {% endfor %}
          {% endif %}
        </div>
        
        <div class="form-group my-2 d-flex justify-content-between">
          {{ form.submit(class="btn w-50 btn-primary me-3") }}
          <a class="btn btn-outline-dark text-decoration-none" href="{{ url_for('users.reset_password', token=current_user.get_password_reset_token()) }}">Update your password?</a>
        </div>
      </fieldset>
    </form>
  </div>
{% endblock content %}

src/templates/create_post.html
{% extends "layouts/base.html" %}
{% block title %}New Blog Post{% endblock title %}

{% block content %}
  <div class="content-section">
    <form method="POST" action="" enctype="multipart/form-data">
      {{ form.hidden_tag() }}
      
      <fieldset class="form-group">
        <legend class="border-bottom-purple mb-3 pb-1">{{ legend }}</legend>
        
        <div class="form-group mb-3">
          {{ form.title.label(class="form-control-label mb-1") }}
          
          {% if form.title.errors %}
            {{ form.title(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.title.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          
          {% else %}
            {{ form.title(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        
        <div class="form-group mb-3">
          {{ form.content.label(class="form-control-label mb-1") }}
          {% if form.content.errors %}
            {{ form.content(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.content.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.content(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        
        <div class="form-group my-2">
          {{ form.submit(class="btn w-50 btn-primary") }}
        </div>
      </fieldset>
    </form>
  </div>
{% endblock content %}

src/templates/home.html
{% extends "layouts/base.html" %}
{% block title %}Home{% endblock title %}

{% block content %}
  {% for post in posts.items %}
    <article class="content-section pb-0 shadow">
      <div class="media border-bottom-purple pb-2 mb-2">
        <div class="row align-items-center">
          <div class="col-auto pe-0">
            <a href="{{ url_for('posts.get_post', post_id=post.id) }}">
              <img class="" style="width: 40px; height: 40px;" alt="User Image" src="{{ url_for('static', filename='profile_photos/' + post.author.photo) }}">
            </a>
          </div>
          
          <div class="col media-body d-grid">
            <div class="small d-flex justify-content-between">
              <a class="text-black text-decoration-none" href="{{ url_for('posts.user_posts', username=post.author.username, page=page_num, per_page=posts.per_page) }}">{{ post.author.username }}</a>
              
              <span class="text-muted">{{ post.date_posted.strftime("%I:%M:%S %p | %d/%m/%Y") }}</span>
            </div>
            
            <div class="overflow-hidden text-nowrap mt-1" style="border-top: 1px solid #adabb1; text-overflow: ellipsis;">
              <a class="text-decoration-none" href="{{ url_for('posts.get_post', post_id=post.id) }}">
                {{ post.title }}
              </a>
            </div>
          </div>
        </div>
      </div>
      <p class="article-content text-muted ps-2 post-content-restrict-length">{{ post.content }}</p>
    </article>
  {% endfor %}
  
  
  {% if posts.total %}
    <div class="d-flex mx-2 justify-content-center align-items-center">
      <a class="btn btn-sm {% if posts.has_prev %} btn-outline-primary {% else %} btn-outline-secondary disabled {% endif %} mb-4 me-1" href="{{ url_for('main.home', page=posts.prev_num, per_page=posts.per_page) }}">&lt;</a>
      
      {# Precompute the pages displayed by iter_pages #}
      {% set displayed_pages = [] %}
      
      {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
          {% set _ = displayed_pages.append(page_num) %}
          <a class="btn btn-sm {% if posts.page != page_num %} btn-outline-primary {% else %} btn-outline-secondary disabled {% endif %} mb-4 me-1" href="{{ url_for('main.home', page=page_num, per_page=posts.per_page) }}">{{ page_num }}</a>
        {% else %}
          <div class="btn btn-sm text-muted px-0 me-1 mb-4">...</div>
        {% endif %}
      {% endfor %}
      
      <a class="btn btn-sm {% if posts.has_next %}btn-outline-primary{% else %} btn-outline-secondary disabled {% endif %} mb-4 me-3" href="{{ url_for('main.home', page=posts.next_num, per_page=posts.per_page) }}">&gt;</a>
      
      <div class="text-muted px-0 me-1 mb-4">
        <form action="{{ url_for('main.home') }}" method="GET">
          <div class="input-group input-group-sm">
            <input type="number" class="form-control" name="page" placeholder="Page" min="1" max="{{ posts.pages }}">
            <button type="submit" class="btn btn-primary btn-sm">Go</button>
          </div>
        </form>
      </div>
    </div>
  
  {% else %}
    <div class="alert alert-primary text-center" role="alert">
      <h4 class="alert-heading">No Posts Yet!</h4>
      <p class="mb-0">Be the first to post something!</p>
    </div>
  {% endif %}->
{% endblock content %}

src/templates/login.html
{% extends "layouts/base.html" %}
{% block title %}Login{% endblock title %}


{% block content %}
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      
      <fieldset class="form-group">
        <legend class="border-bottom-purple mb-3 pb-1">Login with your account</legend>
        
        <div class="form-group mb-3">
          {{ form.email.label(class="form-control-label mb-1") }}
          
          {% if form.email.errors %}
            {{ form.email(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          
          {% else %}
            {{ form.email(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        
        <div class="form-group mb-3">
          {{ form.password.label(class="form-control-label mb-1") }}
          {% if form.password.errors %}
            {{ form.password(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.password.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.password(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        
        <div class="row form-group border-bottom-purple my-2 pb-2 align-items-center">
          <div class="col form-group">
            {{ form.submit(class="col-12 btn btn-primary") }}
          </div>
          
          <div class="col">
            <div class="form-check">
              {{ form.remember(class="form-check-input") }}
              {{ form.remember.label(class="form-check-label") }}
            </div>
            
            <div class="small text-muted">
              <a class="text-decoration-none border-top-purple" href="{{ url_for('users.reset_password_request') }}">Forgot Your Password?</a>
            </div>
          </div>
        </div>
      </fieldset>
    </form>
    
    <div class="small text-muted">
      Don't Have An Account? <a href="{{ url_for('users.register') }}" class="ms-2">Sign Up</a>
    </div>
  </div>
{% endblock content %}

src/templates/post.html
{% extends "layouts/base.html" %}
{% block title %}Home{% endblock title %}

{% block content %}
  <article class="content-section pb-0 shadow">
    <div class="media border-bottom-purple pb-2 mb-2">
      <div class="row align-items-center">
        <div class="col-auto pe-0">
            <a href="{{ url_for('posts.get_post', post_id=post.id) }}">
              <img class="" style="width: 40px; height: 40px;" alt="User Image" src="{{ url_for('static', filename='profile_photos/' + post.author.photo) }}">
            </a>
        </div>
        
        <div class="col media-body d-grid">
          <div class="row small d-flex justify-content-between">
            <div class="col-auto">
              <a class="text-muted text-decoration-none" href="{{ url_for('posts.user_posts', username=post.author.username, page=page_num, per_page=per_page) }}">{{ post.author.username }}</a>
              
              {% if current_user.id == post.author.id %}
                <div class="dropdown d-inline-block">
                  <button class="btn btn-sm p-0 m-0 btn-link dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  </button>
                  
                  <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                    <a class="dropdown-item link-danger" data-bs-toggle="modal" data-bs-target="#deletPost" href="{{ url_for('posts.user_posts', username=post.author.username, page=page_num, per_page=per_page) }}">Delete</a>
                    <a class="dropdown-item" href="#">Hide Post</a>
                  </div>
                </div>
              {% endif %}
            </div>
            
            <span class="col-auto text-muted">{{ post.date_posted.strftime("%I:%M:%S %p | %d/%m/%Y") }}</span>
          </div>
          
          <div class="mt-1" style="border-top: 1px solid #adabb1;">{{ post.title }}</div>
        </div>
      </div>
    </div>
    <p class="article-content ps-2">{{ post.content }}</p>
  </article>
  
  <!-- Modal -->
  <div class="modal fade" id="deletPost" tabindex="-1" aria-labelledby="deletPostLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="deletPostLabel">Delete This Post</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Are you sure you want to delete this post?
        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Confirm">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

src/templates/reset_password_form.html
{% extends "layouts/base.html" %}
{% block title %}Reset Password{% endblock title %}


{% block content %}
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      
      <fieldset class="form-group">
        <legend class="border-bottom-purple mb-3 pb-1">Reset Your Password</legend>
        
        <div class="form-group mb-3">
          {{ form.password.label(class="form-control-label mb-1") }}
          
          {% if form.password.errors %}
            {{ form.password(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.password.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          
          {% else %}
            {{ form.password(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        
        <div class="form-group mb-3">
          {{ form.confirm_password.label(class="form-control-label mb-1") }}
          
          {% if form.confirm_password.errors %}
            {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.confirm_password.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          
          {% else %}
            {{ form.confirm_password(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        
        <div class="row form-group border-bottom-purple my-2 pb-2 align-items-center">
          {{ form.submit(class="col-12 btn btn-primary") }}
        </div>
      </fieldset>
    </form>
    
    <div class="small text-muted">
      Don't Have An Account? <a href="{{ url_for('users.register') }}" class="ms-2">Sign Up</a>
    </div>
  </div>
{% endblock content %}

src/templates/reset_password_request.html
{% extends "layouts/base.html" %}
{% block title %}Password Reset Request{% endblock title %}


{% block content %}
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      
      <fieldset class="form-group">
        <legend class="border-bottom-purple mb-3 pb-1">Reset Your Password</legend>
        
        <div class="form-group mb-3">
          {{ form.email.label(class="form-control-label mb-1") }}
          
          {% if form.email.errors %}
            {{ form.email(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          
          {% else %}
            {{ form.email(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        
        <div class="form-group border-bottom-purple my-2 pb-2 align-items-center">
          {{ form.submit(class="btn btn-primary") }}
        </div>
      </fieldset>
    </form>
    
    <div class="small text-muted">
      Don't Have An Account? <a href="{{ url_for('users.register') }}" class="ms-2">Sign Up</a>
    </div>
  </div>
{% endblock content %}

src/templates/user_posts.html
{% extends "layouts/base.html" %}
{% block title %}Posts By {{ user.username }}{% endblock title %}

{% block content %}
  <div class="h1 text-center mb-4">Posts By {{ user.username }} ({{ posts.total }})</div>
  
  {% for post in posts.items %}
    <article class="content-section pb-0 shadow">
      <div class="media border-bottom-purple pb-2 mb-2">
        <div class="row align-items-center">
          <div class="col-auto pe-0">
            <a href="{{ url_for('posts.get_post', post_id=post.id) }}">
              <img class="" style="width: 40px; height: 40px;" alt="User Image" src="{{ url_for('static', filename='profile_photos/' + post.author.photo) }}">
            </a>
          </div>
          
          <div class="col media-body d-grid">
            <div class="small d-flex justify-content-between">
              <span class="text-muted text-decoration-none">{{ user.username }}</span>
              <span class="text-muted">{{ post.date_posted.strftime("%I:%M:%S %p | %d/%m/%Y") }}</span>
            </div>
            
            <div class="overflow-hidden text-nowrap mt-1" style="border-top: 1px solid #adabb1; text-overflow: ellipsis;">
              <a class="text-decoration-none" href="{{ url_for('posts.get_post', post_id=post.id) }}">
                {{ post.title }}
              </a>
            </div>
          </div>
        </div>
      </div>
      <p class="article-content text-muted ps-2 post-content-restrict-length">{{ post.content }}</p>
    </article>
  {% endfor %}
  
  
  {% if posts.total %}
    <div class="row d-inline-flex mx-2 justify-content-center align-items-center">
      <a class="col btn btn-sm btn-outline-primary {% if not posts.has_prev %}disabled{% endif %} mb-4 me-1" href="{{ url_for('posts.user_posts', username=user.username, page=posts.prev_num, per_page=posts.per_page) }}">Previous</a>
      
      {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
          <a class="col btn btn-sm btn-outline-primary {% if posts.page == page_num %}disabled{% endif %} mb-4 me-1" href="{{ url_for('posts.user_posts', username=user.username, page=page_num, per_page=posts.per_page) }}">{{ page_num }}</a>
        {% else %}
            <div class="col-auto text-muted px-0 me-1 mb-4">...</div>
        {% endif %}
      {% endfor %}
      
      <a class="col btn btn-sm btn-outline-primary {% if not posts.has_next %}disabled{% endif %} mb-4 me-1" href="{{ url_for('posts.user_posts', username=user.username, page=posts.next_num, per_page=posts.per_page) }}">Next</a>
    </div>
    {% else %}
      <div class="alert alert-primary text-center" role="alert">
        <h4 class="alert-heading">No Posts Yet!</h4>
        <p class="mb-0">Post your first blog <a href="{{ url_for('posts.create_post') }}">now</a>!</p>
      </div>
    {% endif %}
{% endblock content %}