src/posts/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, abort, request
from flask_login import current_user, login_required
from blog import db
from users.models import User
from posts.models import Post
from posts.forms import PostForm

posts = Blueprint("posts", __name__)

@posts.route("/post/new", methods=["GET", "POST"])
@login_required
def create_post():
    form = PostForm()
    
    if form.validate_on_submit():
        db.session.add(Post(
            title=form.title.data,
            content=form.content.data,
            author=current_user))
        
        db.session.commit()
        
        flash("Your post has been created successfully.", "success")
        
        return redirect(url_for("main.home"))
    
    return render_template("create_post.html", form=form, legend="Write A New Blog Post")

@posts.route("/post/<int:post_id>")
def get_post(post_id):
    post = Post.query.get_or_404(post_id)
    
    return render_template("post.html", post=post)

@posts.route("/post/<int:post_id>/update", methods=["GET", "POST"])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    
    if post.author != current_user:
        abort(403)
    
    form = PostForm()
    
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        
        db.session.commit()
        
        flash("Your post has been updated successfully.", "success")
        
        return redirect(url_for("posts.get_post", post_id=post.id))
    
    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content
    
    return render_template("create_post.html", form=form, legend="Update Post")


@posts.route("/post/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    
    if post.author != current_user:
        abort(403)
    
    db.session.delete(post)
    db.session.commit()
    
    flash("Your post has been deleted successfully.", "success")
    
    return redirect(url_for("main.home"))


@posts.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get("page", 1, type=int)
    per_page = request.args.get("per_page", 5, type=int)
    
    user = User.query.filter_by(username=username).first_or_404()
    posts=Post.query.filter_by(author=user) \
        .order_by(Post.date_posted.desc()) \
        .paginate(page=page, per_page=per_page)
    
    return render_template("user_posts.html", posts=posts, user=user)

src/users/routes.py
from flask import current_app, render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, logout_user, current_user, login_required
from blog import db, bcrypt
from users.utils import save_picture
from users.forms import RegistrationForm, LoginForm, UpdateAccountForm, ResetPasswordRequestForm, ResetPasswordForm
from users.models import User
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

users = Blueprint("users", __name__)

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    
    form = RegistrationForm()
    
    if form.validate_on_submit():
        db.session.add(User(
            username=form.username.data,
            email=form.email.data,
            password=bcrypt.generate_password_hash(form.password.data).decode("utf-8")))
        
        db.session.commit()
        
        flash("Your account has been created successfully. Please login now.", "success")
        
        return redirect(url_for("users.login"))
    
    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            
            return redirect(request.args.get("next") or url_for("main.home"))
        
        flash("Login Unsuccessful. Please check email and password", "danger")
    
    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
def logout():
    logout_user()
    
    return redirect(url_for("main.home"))


@users.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
    form = UpdateAccountForm()
    
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        
        if form.photo.data:
            image_filename = save_picture(form.photo.data)
            current_user.photo = image_filename
        
        db.session.commit()
        
        flash("Your account info has been updated successfully.", "success")
        
        return redirect(url_for("users.profile")) # POST-GET-Redirect pattern.
    
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    
    return render_template("account.html", form=form)


@users.route("/reset_password_request", methods=["GET", "POST"])
def reset_password_request():
    """
    Description:
        Handles the reset password functionality.
        
        This route allows users to request a password reset by providing their email address. An email with instructions to reset the password is sent to the user's email address. If the user is already authenticated, they are redirected to the home page.
    
    ---
    Returns:
        If the form is submitted and valid, redirects to the login page after sending the password reset email.
        If the user is already authenticated, redirects to the home page.
        Otherwise, renders the reset password request form.
    """
    
    form = ResetPasswordRequestForm()
    
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        token = user.get_password_reset_token()

        server = smtplib.SMTP("smtp.gmail.com:587")
        server.ehlo("Gmail")
        server.starttls()
        server.login(current_app.config["MAIL_ADDRESS"], current_app.config["MAIL_APPWORD"])

        Message = MIMEMultipart()
        Message["From"] = current_app.config["MAIL_ADDRESS"]
        Message["To"] = user.email
        Message["Subject"] = "Password Reset Request."
        
        messageText = MIMEText(f"To reset your password, visit the following link: {url_for('users.reset_password', token=token, _external=True)}","html")
        Message.attach(messageText)

        server.sendmail(current_app.config["MAIL_ADDRESS"], user.email, Message.as_string())
        server.quit()
        
        flash("An email has been sent with instructions to reset your password.", "info")
        
        if current_user.is_authenticated:
            return redirect(url_for("main.home"))
    
        return redirect(url_for("users.login"))
    
    return render_template("reset_password_request.html", form=form)


@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_password(token):
    user = User.verify_password_reset_token(token)
    
    if not user:
        flash("Token is invalid or expired.", "warning")
        
        return redirect(url_for("users.reset_password_request"))
    
    form = ResetPasswordForm()
    
    if form.validate_on_submit():
        user.password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        db.session.commit()
        
        flash("Your password has been updated successfully.", "success")
        
        return redirect(url_for("users.login"))
    
    return render_template("reset_password_form.html", form=form)

src/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock title %}</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
</head>
<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-purple fixed-top shadow">
      <div class="container">
        <a class="navbar-brand d-md-none" href="/">Bloggy</a>
        <a class="navbar-brand d-none d-md-block br-right" href="/">Bloggy</a>
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
            <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
          </div>
          
          <div class="navbar-nav ms-auto">
            
            {% if current_user.is_authenticated %}
              <a class="nav-item nav-link" href="{{ url_for('posts.create_post') }}">New Post</a>
              
              <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="accountDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account </a>
                <div class="dropdown-menu" aria-labelledby="accountDropdown">
                  <a class="dropdown-item" href="{{ url_for('users.profile') }}">Profile</a>
                  <a class="dropdown-item" href="{{ url_for('posts.user_posts', username=current_user.username) }}">User Posts</a>
                  <a class="dropdown-item" href="{{ url_for('users.logout') }}">Logout</a>
                </div>
              </div>
            {% else %}
              <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
              <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>
  
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-{% if show_sidebar %}8{% else %}12{% endif %}">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        
        {% block content %}{% endblock content %}
      </div>
      
      {% if show_sidebar %}
        <div class="col-md-4 d-none d-md-block">
          <div class="content-section pb-3 shadow">
            <h3 class="pb-1 mb-1 border-bottom-purple">Sidebar</h3>
            
            <p class='text-muted'>You can put any information here you'd like.</p>
            
            <ul class="list-group shadow">
              <li class="list-group-item list-group-item-bg-purple">Latest Posts</li>
              <li class="list-group-item list-group-item-bg-purple">Announcements</li>
              <li class="list-group-item list-group-item-bg-purple">Calendars</li>
              <li class="list-group-item list-group-item-bg-purple">etc</li>
            </ul>
          </div>
        </div>
      {% endif %}
    </div>
  </main>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.bundle.min.js"></script>
</body>
</html>